[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/LocalAreaNetwork.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://cdn.jsdmirror.com/gh/Loyalsoldier/surge-rules@release/ruleset/private.txt"
interval = 86400

#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/DivineEngine/Surge/Ruleset/Unbreak.list"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "rules/BlockNetworkCustom.list"

#[[rulesets]]
#group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
#ruleset = "rules/NobyDa/Surge/AdRule.list"

# å¤ªé•¿äº†å…ˆç¦ç”¨
#[[rulesets]]
#group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
#ruleset = "https://cdn.jsdmirror.com/gh/Loyalsoldier/surge-rules@release/ruleset/reject.txt"
#interval = 86400

#[[rulesets]]
#group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
#ruleset = "rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list"

#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
##ruleset = "rules/DivineEngine/Surge/Ruleset/China.list"
#ruleset = "rules/blackmatrix7/rule/Surge/China/China_All.list"

#[[rulesets]]
#group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
#ruleset = "rules/blackmatrix7/rule/Surge/Proxy/Proxy_All.list"

#[[rulesets]]
#group = "â“‚ï¸"
#ruleset = "rules/blackmatrix7/rule/Surge/Microsoft/Microsoft.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/blackmatrix7/rule/Surge/SteamCN/SteamCN.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Sony.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Apple.list"


[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://cdn.jsdmirror.com/gh/Loyalsoldier/surge-rules@release/ruleset/direct.txt"
interval = 86400
# https://jsd.onmicrosoft.cn/gh/Loyalsoldier/surge-rules@release/ruleset/direct.txt

#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Bilibili.list"
#
#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/iQiyi.list"
#
#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Letv.list"
#
#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/MOO.list"
#
#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Tencent Video.list"
#
#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Youku.list"

#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/blackmatrix7/rule/Surge/Download/Download.list"

#[[rulesets]]
#group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
#ruleset = "rules/DivineEngine/Surge/Ruleset/Global.list"

#[[rulesets]]
#group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
#ruleset = "rules/blackmatrix7/rule/Surge/Netflix/Netflix.list"

#[[rulesets]]
#group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
#ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list"

#[[rulesets]]
#group = "ğŸ¯ å…¨çƒç›´è¿"
#ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/StreamingCN.list"

#[[rulesets]]
#group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
#ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Game/Steam.list"

#[[rulesets]]
#group = "âœ‰ï¸ ChatGPT"
#ruleset = "rules/blackmatrix7/rule/Surge/OpenAI/OpenAI.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

